// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MrDZpkwibQ3jrX5EnaDWSggy1KYAjyE',
    appId: '1:263642390295:web:d6f9556ea1b1541f152152',
    messagingSenderId: '263642390295',
    projectId: 'sfac-test-1114f',
    authDomain: 'sfac-test-1114f.firebaseapp.com',
    storageBucket: 'sfac-test-1114f.appspot.com',
    measurementId: 'G-6RCFP0J3NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrDlZag6a34PzXbnMjRq1jtljEb73DDM',
    appId: '1:263642390295:android:b6a87fc0bb311e62152152',
    messagingSenderId: '263642390295',
    projectId: 'sfac-test-1114f',
    storageBucket: 'sfac-test-1114f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MdYeT7M3TMEOKK4VWVvmbsyzrwv8Mu0',
    appId: '1:263642390295:ios:a13bf64e049dd9aa152152',
    messagingSenderId: '263642390295',
    projectId: 'sfac-test-1114f',
    storageBucket: 'sfac-test-1114f.appspot.com',
    iosBundleId: 'com.example.assignment',
  );
}
